# Generated by Django 5.1.6 on 2025-03-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("telegram_id", models.IntegerField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=255)),
            ],
        ),
    ]
